# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 558b47e807dbd72fb3bf69edb620471d1bccbe7239e05728d0f4bb02e65ffd7edc096478d4c807edbbd731c24c3c5483ae5f259fc4e6ce63cd61444b8a5da749

test:
  secret_key_base: f0081b4d918d32afed87d76b38fdc42c9e647865c8c94029ab4fc59b297c874b943276b2c8f1a181d7e7f00aff863b2e564f56e830e7fdb0539d9adf6a961919

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
